### ISSUE TITLE
Accesibility Service can't be turned on

### ISSUE THREAD

**Issue by markguchi** [d4rken-org/sdmaid-se#1002]
**Describe the bug**
Accessibility service for the app can't be turned on. Turning on returns an error message somehwere along the lines of "there's a problem with the service". This also hinders me from doing any cleaning task.  

**To Reproduce**
1. Go to the Setting app
2. Navigate to Accessibility settings
3. Select SD Maid SE
4. Turn on service

**Expected behavior**
The service should turn on and I should be able to proceed with cleaning. 

**Smartphone (please complete the following information):**
 - Device: Xiami Redmi Note 10 Pro
 - OS: MIUI 14.0.8 (Android 13)
 - Root status [e.g. Rooted - Magisk v25.2]
 - Build: `v0.19.1-beta0 (1901000) ~ 571ed824/GPLAY/BETA`
Update history: `[0.19.1-beta0]`
ROM: `Redmi/sweet_global/sweet:13/TKQ1.221013.002/V14.0.8.0.TKFMIXM:user/release-keys`

**Comment by d4rken** [comment]
Try these FAQs:

https://github.com/d4rken-org/sdmaid-se/wiki/Setup#acs-troubleshooting

If neither helps I'll need a debug log to investigate this further.
Reboot the phone, enable the debug log, and then try to enable the service:
https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log

**Comment by RileyMarquis3** [comment]
I have a different device, but what fixed it for me was the troubleshooting link @d4rken provided.  
Turns out my copy of the app was installed via Chrome rather than the Play Store.  I uninstalled and reinstalled from the Play Store and got it working. 

You can see where the app was installed from at the bottom of the screen when you go to Settings--->Apps--->SD Maid SE.  I believe the app may have a different signature on Github vs Play Store, as some things show up somewhat differently, but it appears to be completely cosmetic.

The only remaining difference is that as of today 02/11/2024, Play Store has version 0.19 and GitHub has 0.20 (Released 3 days ago).
