### ISSUE TITLE
Wrong storage label

### ISSUE THREAD

**Issue by lukaskretzschmer** [d4rken-org/sdmaid-se#1010]
**Describe the bug**
The storage label says primary but the app is stored on the external storage. 

**To Reproduce**
Analyze the used primary storage 
Select an app that you know is on the external storage 
Check the label, it will say primary but in the phone settings it says external. 

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 9]
 - OS: [e.g. Android 17]
 - Root status [e.g. Rooted - Magisk v25.2]
 - SD Maid 2/SE version [e.g. v0.6.6-rc6]

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.
![Screenshot_20240209-104420_SD Maid SE.jpg](https://github.com/d4rken-org/sdmaid-se/assets/29391908/da0baee6-526f-4aef-b962-49c20a1ff4d8)

![Screenshot_20240209-104428_Settings.jpg](https://github.com/d4rken-org/sdmaid-se/assets/29391908/49b07d7b-aa02-4cf4-96ab-0bf78dcb97dd)

**Additional context**

**Comment by d4rken** [comment]
What device and ROM is this?
Can you get me a debug log of this?

The analyzer shows "per storage", so if you clicked on "primary storage" and then the app, then it should say primary storage.

The bug here could be that it shows 4GB occupied here, whereas the "4GB" are on the external storage and not the primary one :thinking:
