### ISSUE TITLE
Inclusion to F-Droid main repository

### ISSUE THREAD

**Issue by ClockGen** [d4rken-org/sdmaid-se#1043]
Hello, I've been working on getting to build SDMain-SE on F-Droid infrastructure. The inclusion process is similar to your other app (Capod), which is already in F-Droid, however everything seems to be already covered in https://github.com/d4rken-org/sdmaid-se/issues/755.  

The app builds and verifies fine (it's in my private branch for now), but I need your permission to include it in F-Droid.

Another thing, can you please change the apk naming scheme and remove the commit hash suffix, so it'd look like this:
`eu.darken.sdmse-v0.21.0-beta0-2100000-FOSS-BETA.apk`
(same naming scheme as Capod). This is needed to allow F-Droid to retrieve your apk for reproducible builds.

I can also work on getting your other apps (permission pilot and octi) to F-Droid, if you want.

**Comment by d4rken** [comment]
As far as I understood, it's not possible to include SD Maid 2/SE in the main F-Droid repo because it has the "anti-feature" `NonFreeAssets`. 

Code is GPLv3, but not all assets are (see README.md). I currently have no plans to change that, sorry.

I'm fine with it just being available in @IzzySoft's repo:
https://apt.izzysoft.de/fdroid/index/apk/eu.darken.sdmse

FYI, there also appears to be an open PR here:
https://gitlab.com/fdroid/rfp/-/issues/2533

Side-note: `CAPod` is included in F-Droid, but it has the same license-caveat/anti-feature. That might have been a mistake? Or I'm mistaken with the anti-feature requirements of the main repo :thinking:

**Comment by IzzySoft** [comment]
@d4rken `NonFreeAssets` is just an anti-feature, not a show-stopper, at F-Droid. the corresponding RFP you've linked was not rejected – it's just nobody working on it.

That said, I'm fine keeping your app in my repo :smile:

**Comment by ClockGen** [comment]
As Izzy said, antifeatures don't prevent apps from being included in F-Droid.

> t's just nobody working on it.  

Well, I'm working on it, that's why I ask for permission to publish it in main repo.

**Comment by shuvashish76** [comment]
@ClockGen @d4rken Instructions are mentioned [here](https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md#merge-requests).

**Comment by d4rken** [comment]
#1186 changes the naming scheme of the exported apk.

You can include SD Maid 2/SE in the F-Droid main repo :+1:

Thanks and sorry for the long silence, life is busy sometimes :beers:.

**Comment by linsui** [comment]
Great! When will there be a new release with that change?

**Comment by d4rken** [comment]
Probably some time this week.

FYI: I'm also considering making it the first v1.0 release as the current builds are quite stable.

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15094 Reproducible build works. As soon as the new release is published I'll update and merge it.

The version.properties can't be found when I build the apk in app dir. Could you please fix that?

Will you use the release buildType for the next version?

**Comment by d4rken** [comment]
> The version.properties can't be found when I build the apk in app dir. Could you please fix that?

Not sure what to fix here. Can you elaborate?

**Comment by linsui** [comment]
It should load version.properties from the root dir instead of the current dir. https://github.com/d4rken-org/sdmaid-se/blob/main/buildSrc/src/main/java/ProjectConfig.kt#L32

**Comment by d4rken** [comment]
Hm, I'm actually not sure how to get a reference to the root project path there :thinking:, `rootProject` isn't available from the `buildSrc` scripts...

Why was this not an issue in [CAPod](https://github.com/d4rken-org/capod), where the build script is the same?

Wouldn't you normally check out the project, whole, then run `gradle :app:assemble...` from the root directory?

**Comment by linsui** [comment]
> Why was this not an issue in [CAPod](https://github.com/d4rken-org/capod), where the build script is the same?

It is since the first version included. :) See https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/eu.darken.capod.yml#L28.

We can run gradle manually but by default we run it from `app` and calculate the apk path automatically.

**Comment by linsui** [comment]
Is [v1.0.0-rc0](https://github.com/d4rken-org/sdmaid-se/releases/tag/v1.0.0-rc0) ready?

**Comment by d4rken** [comment]
It's fully released on Google Play and GitHub. No reports about any major issues so far.

**Comment by shuvashish76** [comment]
Live on F-Droid : https://f-droid.org/en/packages/eu.darken.sdmse/ 🎉
App icon & screenshots missing as nothing added to fastlane.
Feel free to use their badge : https://gitlab.com/fdroid/artwork/-/blob/master/badge/README.md

**Comment by d4rken** [comment]
I moved icon and screenshots to use the `fastlane supply` structure. Does this work automatically when the next release happens?

**Comment by IzzySoft** [comment]
Yes, F-Droid will pick it up automatically. For IzzyOnDroid, I've just adjusted the config to also pick up the icon and the screenshots. Full description I've converted manually here as it wouldn't format fine otherwise (I could take it the same way F-Droid does, simply converting all line breaks to `<br>`, but that would e.g. make the bullet-point lists look a little broken on smaller screens). If you want me to, I could take the current `full_description.txt`, manually format it and send it back to you. Two variants to pick from:

"Markdown compatible":

```markdown
<i>SD Maid 2/SE</i> is your Android’s trusted assistant, to keep it clean and tidy.

Nobody is perfect and neither is Android.

* Apps you have already removed leave something behind.
* Logs, crash reports and other files you don't want are constantly being created.
* Your storage is collecting files and folders you don't recognize.
* Duplicate photos in your gallery.

Let’s not go on here… Let SD Maid 2/SE help you!

SD Maid 2/SE is an app and file manager that specializes in knowing which apps have created specific files on your device. SD Maid 2/SE searches your device and compares files with installed apps to offer options for safely freeing up storage space.

<b>✨ Clean up after uninstalling apps</b>

If apps create files outside their designated folders then files can remain even after uninstalling the apps. The "CorpseFinder" tool finds app remains, tells you to which app they belonged and helps you delete them.

<b>🔍 Search your device the smart way</b>
Filter for empty folders, temporary files, already installed apps and more. You can even create your own search criteria. The "SystemCleaner" tool allows you to automatically search your device and delete files based on various criteria.

…
```

or full-fledged HTML (which I'd then suggest to "compress" to a single line as otherwise F-Droid would still add `<br>s for each line break).

**Comment by d4rken** [comment]
The smallest common denominator should be: "what does google play support".

I don't think gplay supports full markdown, right? AFAIK gplay supports a small subset of HTML? :thinking:

**Comment by linsui** [comment]
F-Droid also only supports a subset of HTML. I thought it should work everywhere.

**Comment by IzzySoft** [comment]
> I don't think gplay supports full markdown

Not speaking about "full Markdown" here, but about what I call "Markdown lite". That's what all 3 mentioned parties support:

* F-Droid would simply replace all newlines with `<br>` and support the HTML tags used (bold, italics etc)
* PlayStore would do the same
* IzzyOnDroid would convert it from Markdown to proper HTML (which F-Droid clients support) and use that then, which will look much better than what the former two produce.

For details, be welcome to the [IzzyOnDroid Fastlane Documentation](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane#formatting-descriptions) (link goes directly to the corresponding section on formatting descriptions).

> I thought it should work everywhere.

Which is what "Markdown lite" does. Proven hundreds of times (remember the IzzyOnDroid repo exists since 2016, so I had a lot of time to confirm this :wink:). And as the linked documentation shows: it takes into consideration what F-Droid and Google support, yes. So 100% compatible.

**Comment by d4rken** [comment]
I think this part can be considered done :partying_face:.

@IzzySoft @linsui Can we change the contact email to `support@darken.eu`? :pray:

**Comment by linsui** [comment]
Done. :)

**Comment by IzzySoft** [comment]
Here as well (effective with the next sync around 7 pm UTC). For your other apps (bluemusic, capod, myperm, octi) as well I guess?

**Comment by d4rken** [comment]
> Here as well (effective with the next sync around 7 pm UTC). For your other apps (bluemusic, capod, myperm, octi) as well I guess?

That would be great, thank you!

**Comment by IzzySoft** [comment]
Done :smiley:
