### ISSUE TITLE
app exclusion doesn't seems to be respected by storage analyzer

### ISSUE THREAD

**Issue by theotheroracle** [d4rken-org/sdmaid-se#1122]
**Describe the bug**
after adding a full app exclusion for an app, storage analyzer still tries to scan it

**To Reproduce**
1. add an exclusion for an app through app control
2. run storage analyzer

**Expected behavior**
the app would not be scanned

**Smartphone (please complete the following information):**
 - Device: oneolus 6
 - OS: lineage 21
 - Root status: Rooted - Magisk v27
 - SD Maid 2/SE version: v0.23.3-beta0

**Comment by theotheroracle** [comment]
[eu.darken.sdmse_logfile_1712430751959.zip](https://github.com/d4rken-org/sdmaid-se/files/14894741/eu.darken.sdmse_logfile_1712430751959.zip)

**Comment by d4rken** [comment]
This is currently by design. Exclusions don't work against the StorageAnalyzer because for some of the calculations we substract the sizes from other apps, e.g. SYSTEM = STORAGE_SIZE - MEDIA - APPS. Excluding apps would make the result incorrect.

Can you elaborate on your use-case? Which app are you trying to exclude and why?

**Comment by theotheroracle** [comment]
I was trying to exclude nix because the searching process would stall there for a very long time, I don't know the longest time I waited, but it never completed

**Comment by d4rken** [comment]
Is this still an issue?

In one of the updates I made some of the app data loading "on-demand" which should help with this.
