### ISSUE TITLE
Tablet Layout

### ISSUE THREAD

**Issue by alabotski** [d4rken-org/sdmaid-se#1126]
On latest versions (> 0.21.0)
Changed design on tablets

Previously there was one column (like on a phones), now there are two

[Screenshot_20240406-210757_SD Maid SE](https://github.com/d4rken-org/sdmaid-se/assets/439337/d8f53500-f6d3-487b-b1b8-98faa9378a51)
[Screenshot_20240406-210843_SD Maid SE](https://github.com/d4rken-org/sdmaid-se/assets/439337/ac6b4309-c12f-4217-a7b3-39b1fd3160ac)

**Comment by d4rken** [comment]
That's intentional, the default card size is set as the normal phone width. If the screen is twice as wide, then multiple columns are used. I think this is a better use of space, streching the entires does not look that good. What do you think?

https://github.com/d4rken-org/sdmaid-se/blob/d0fb8aa75c13fc67ffad88cbc1d2c865560779d1/app-common/src/main/java/eu/darken/sdmse/common/ContextExtensions.kt#L73-L80
