### ISSUE TITLE
SD Maid stays open after using automation in the background via scheduler

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid-se#1197]
Exists since v0.24.0, the fix in v1.0.0-rc0 didn't solve the issue

If SD Maid is not open, and the scheduler launches and uses automation/accessibility service, SD Maid is opened afterwards.

Also see #1161 which didn't fix this issue

**Comment by MarkyMarkDE** [comment]
Thank you for filing this issue again. Since you removed something for never existing back function (so I remember the reason), we have trouble with that. It must be possible to reproduce for you.
I'm on Standard Pixel 7 with the current patches, no root, no shi Dingsda, usw. only a normal Pixel and the same on a normal AndroidTV (12?) on a waipu.tv 4k Stick.

**Comment by MarkyMarkDE** [comment]
You have not tried to fix that for 1.0.1?
