### ISSUE TITLE
Long SystemCleaner scan due to `/data/rootfs`

### ISSUE THREAD

**Issue by zhangweildlh** [d4rken-org/sdmaid-se#1331]
﻿
**Describe the bug**
1. Click on 'SystemCleaner'
2. Stuck in the 'Scanning' phase；Continuous scan, unable to end scan
﻿
**Expected behavior**
I hope to successfully complete the scan and clean up the 'system junk files'
﻿
**Smartphone (please complete the following information):**
- Device: [e.g. Pixel 9]  Xiaomi Pad 5 Pro
- OS: [e.g. Android 17] Xiaomi HyperOS 1.0.1.0 ( Android 14)
- Root status [e.g. Rooted - Magisk v25.2]  27.0(27000)
- SD Maid 2/SE version [e.g. v0.6.6-rc6]  1.2.1-rc0
﻿
**Debug log**
debug-log：eu.darken.sdmse_logfile_1722181652032.zip
[eu.darken.sdmse_logfile_1722181652032.zip](https://github.com/user-attachments/files/16404421/eu.darken.sdmse_logfile_1722181652032.zip)

﻿
**Screenshots/Video**
[Screenshots.zip](https://github.com/user-attachments/files/16404452/Screenshots.zip)

﻿
﻿

**Comment by d4rken** [comment]
Not stuck, just scanning lots of files in `/data/rootfs`.

Try creating an exclusion for that path and let me know if it works.

I don't think there is any good reasons for SD Maid to scan that path, no good targets in there, maybe we add a default exclusion :thinking:

**Comment by Alberto16012020** [comment]
> **Describe el error**
> 
> 1. Haga clic en 'SystemCleaner'
> 2. Atascado en la fase de 'Escaneo'; Escaneo continuo, no se puede finalizar el escaneo 
>    ﻿
>    **Comportamiento esperado**  
>    Espero completar con éxito el escaneo y limpiar los 'archivos basura del sistema' 
>    ﻿
>    **Teléfono inteligente (completa la siguiente información):**
> 
> * Dispositivo: [p. ej. Píxel 9] Xiaomi Pad 5 Pro
> * Sistema operativo: [por ejemplo, Android 17] Xiaomi HyperOS 1.0.1.0 (Android 14)
> * Estado de raíz [por ejemplo, Rooteado - Magisk v25.2] 27.0(27000)
> * Versión de SD Maid 2/SE [p. ej. v0.6.6-rc6] 1.2.1-rc0 
>   ﻿
>   **Registro de depuración**  
>   debug-log：eu.darken.sdmse_logfile_1722181652032.zip 
>   [eu.darken.sdmse_logfile_1722181652032.zip](https://github.com/user-attachments/files/16404421/eu.darken.sdmse_logfile_1722181652032.zip)
> 
> ﻿ **Capturas de pantalla/ ** [Capturas de pantalla de vídeo.zip](https://github.com/user-attachments/files/16404452/Screenshots.zip)

**Comment by enadvip9565162** [comment]
Hello
Thank you guys for trying to help I have seen it by chance, I don't know even how it got here me trying to create a path testing things I been in circles with hacker using shadow x and restore network points, he planned everything truly and cut me out of the world .
Now it came to really hurting and harming family, he fot my wife and baby girl devices 
He is really good , expert I mean I didn't see this level this long with different systems which made me call for help by phone and email but nothing happened but ignoring from that entity 
If you can and willing to help I'll be happy to share all the details, logs, systems he use , he cast 24/7 , picture to picture, video, ect everything fully control.

**Comment by enadvip9565162** [comment]
I have Red magic 8s pro nit rooted.
I installed some apps to corner him I'm new to this never done it before, I had nothing else to do the SD maid for some time stopped him partially but he already have complete system, reset , or boot dynamic loader same thing

**Comment by enadvip9565162** [comment]
I have Red magic 8s pro/ also my laptop HP victos gaming 15 16/512/i7. Win 11

RAM capacity
16 GB + 12 GB

Storage
447.96 GB/512 GB

Model
NX729J >

CPU
Snapdragon 8 Gen 2 Mobile Platform Leading Version
Octa-core Max 3.36GHz

Screen
2480*1116

Battery capacity
6000 mAh

IMEI
865590066476502
865590066487509

>

Build number
REDMAGICOS9.5.3_NX729J_GB

**Comment by emran349** [comment]
> **Describe the bug**
> 
> 1. Click on 'SystemCleaner'
> 2. Stuck in the 'Scanning' phase；Continuous scan, unable to end scan
>    ﻿
>    **Expected behavior**
>    I hope to successfully complete the scan and clean up the 'system junk files'
>    ﻿
>    **Smartphone (please complete the following information):**
> 
> * Device: [e.g. Pixel 9]  Xiaomi Pad 5 Pro
> * OS: [e.g. Android 17] Xiaomi HyperOS 1.0.1.0 ( Android 14)
> * Root status [e.g. Rooted - Magisk v25.2]  27.0(27000)
> * SD Maid 2/SE version [e.g. v0.6.6-rc6]  1.2.1-rc0
>   ﻿
>   **Debug log**
>   debug-log：eu.darken.sdmse_logfile_1722181652032.zip
>   [eu.darken.sdmse_logfile_1722181652032.zip](https://github.com/user-attachments/files/16404421/eu.darken.sdmse_logfile_1722181652032.zip)
> 
> ﻿ **Screenshots/Video** [Screenshots.zip](https://github.com/user-attachments/files/16404452/Screenshots.zip)

**Comment by Drey014** [comment]
﻿
**Describe the bug**
1. Click on 'SystemCleaner'
2. Stuck in the 'Scanning' phase；Continuous scan, unable to end scan
﻿
**Expected behavior**
I hope to successfully complete the scan and clean up the 'system junk files'
﻿
**Smartphone (please complete the following information):**
- Device:[Tecno KJ7] Spark 20 pro +
- OS: HiOS V13.6.0. ( Android 14)
- Root status [Not Rooted] 
- SD Maid 2/SE version [v1.7.4-rc0]
﻿
**Debug log**
debug-log：eu.darken.sdmse_logfile_1722181652032.zip
[eu.darken.sdmse_logfile_1722181652032.zip](https://github.com/user-attachments/files/16404421/eu.darken.sdmse_logfile_1722181652032.zip)

﻿
**Screenshots/Video**
[Screenshots.zip](https://github.com/user-attachments/files/16404452/Screenshots.zip)

﻿
﻿

**Comment by MarkyMarkDE** [comment]
> Addiotional Infos

@enadvip9565162 

The original issue was reported in **July 2024**, when this software stack was current. Your current setup is still based on that very same software stack almost two years later. Darken already marked this issue as fixed in [v1.2.2-rc0](https://github.com/d4rken-org/sdmaid-se/releases/tag/v1.2.2-rc0).

Please update your device to the latest available official system version before reporting or reproducing issues.

Please update SD-Maid itself first (you are running **v1.2.2-rc0 from Jun 24, 2024**). We are currently running [_v2.0.1-beta1_](https://github.com/d4rken-org/sdmaid-se/releases/tag/v2.0.1-beta1) from **Jul 23, 2026**.

Last but not least: You are **2(!)** YEARS behind with your update.

So we will NOT take a look at your issue under your current installation status, sorry. We won't spend our free time investigating issues on an almost two-year-old software stack when the bug may not even exist anymore.

If your problem still occurs after updating your whole system AND SD-Maid to the current version, please open a new ticket (with a fresh [debug.log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs) attached) and reference this ticket (#1331).
BTW: All modern SD-Maid versions have automatic self-updates enabled by default, so you will always be up to date unless you disable them. 😉
