### ISSUE TITLE
Error when checking root access

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid-se#153]
Ошибка, версия 0.7.1

[IMG_20230412_040948](https://user-images.githubusercontent.com/60130882/231321418-f6d74181-ca53-4b28-b5f5-0874a1d8f135.jpg)

**Comment by d4rken** [comment]
Can you share a debug log?

**Comment by Ingood5** [comment]
[eu.darken.sdmse_logfile_1681367157520.log.zip](https://github.com/d4rken-org/sdmaid-se/files/11218805/eu.darken.sdmse_logfile_1681367157520.log.zip)

**Comment by d4rken** [comment]
Did you allow SD Maid to use root in the setup process?

This may be a migration issue from an older version.

The setup step is new where SD Maid asks first before just popping up the root dialog.

**Comment by Ingood5** [comment]
> Did you allow SD Maid to use root in the setup process?

Ошибка появляется при выборе любого варианта в процессе установки

**Comment by d4rken** [comment]
So this is enabled in Setup? :thinking: 
Did you try a fresh install?

![Screenshot from 2023-05-16 07-25-00](https://github.com/d4rken-org/sdmaid-se/assets/1439229/22a7813d-9480-4a3f-b548-44be87fb81fd)

**Comment by Ingood5** [comment]
Да, я попробовал оба варианта с вашего скриншота

**Comment by d4rken** [comment]
I currently have no solution for this, the error log from your initial posts shows:

`RootUnavailableException: Root is not enabled` which would mean that the setup was not completed:

https://github.com/d4rken-org/sdmaid-se/blob/8ec3847ae90448b56173b65a6a9122564aa8a0eb/app-common-io/src/main/java/eu/darken/sdmse/common/root/service/RootServiceClient.kt#L29

My only idea would to reinstall SD Maid and make sure not to restore any old data.

What does the debug card show when you run `Test root`?

<img width="334" alt="Screenshot 2023-06-06 at 14 49 56" src="https://github.com/d4rken-org/sdmaid-se/assets/1439229/7c7f3fae-30e6-4048-9da3-76641b18ffda">

**Comment by Ingood5** [comment]
> What does the debug card show when you run `Test root`?

Что такое "debug card"? Если вы про кнопку "view log" с вашего скриншота, то у меня такой нет: 

![Screenshot_2023-06-20-12-10-23-297_eu darken sdmse](https://github.com/d4rken-org/sdmaid-se/assets/60130882/788f0063-0d3f-4003-977b-2dda6ab0be28)

**Comment by Ingood5** [comment]
> My only idea would to reinstall SD Maid and make sure not to restore any old data.

Удалил SD Maid и установил заново, проблема осталась.

**Comment by d4rken** [comment]
I don't understand why it says `Consent=false`.

If you allowed access during setup, and even if there is an error with root, it should still say `Consent=true`.

**No consent given:**

![Screenshot from 2023-06-20 13-49-32](https://github.com/d4rken-org/sdmaid-se/assets/1439229/6cb63e04-03d1-4fbc-be7b-28f1170cea53)
![Screenshot from 2023-06-20 13-49-23](https://github.com/d4rken-org/sdmaid-se/assets/1439229/cfd4b68c-d920-4b86-8698-a1fa4b8c2190)

**Consent given and root allowed in Magisk:**

![Screenshot from 2023-06-20 13-51-35](https://github.com/d4rken-org/sdmaid-se/assets/1439229/a8cfbbaf-d21a-41ae-8cf1-b92aa2b34cae)
![Screenshot from 2023-06-20 13-49-45](https://github.com/d4rken-org/sdmaid-se/assets/1439229/9759aa39-252f-4168-8384-ef54b711124c)


**Consent given but root NOT allowed in Magisk:**

Note how it still says `Consent=true` because in the setup dialog of SD Maid, root was allowed. But in your screenshots it says `Consent=false`. :question: 

![Screenshot from 2023-06-20 13-54-30](https://github.com/d4rken-org/sdmaid-se/assets/1439229/89e753fa-3645-4bef-bbf1-c97416b4c42c)

![Screenshot from 2023-06-20 13-53-04](https://github.com/d4rken-org/sdmaid-se/assets/1439229/2a53ebb9-96b1-46d0-b5ba-b37465f97541)

**Comment by Ingood5** [comment]
У меня сообщения точно такие же как на ваших скриншотах (пункт "Consent given and root allowed in Magisk" не могу проверить т.к. рута у меня нет). Если так и должно быть, то видимо ошибки с самого начала не было 😧. В старых версиях при нажатии кнопки "test root" никакой текст не появлялся. Когда текст стал появляться я решил что это какой-то сбой, в содержание текста я не вникал. Consent=tru и Consent=false у меня тоже как на скриншотах.

**Comment by d4rken** [comment]
Then it was all a big misunderstanding :laughing:.
