### ISSUE TITLE
App Cleaner: Tapping apps' icons does nothing

### ISSUE THREAD

**Issue by uli-on** [d4rken-org/sdmaid-se#288]
**Describe the bug**
In the app cleaner tool, tapping an app's icon does not open the prompt, while tapping an app's name does. 

**To Reproduce**
1. Use App Cleaner's scan button and wait for the eye button to appear. 
2. Tap the eye button. The list with apps comes up. 
3. Tap an app's icon: nada

**Expected behavior**
Tbe prompt appears with the options I have. 

**Smartphone:**
 - Device: Fairphone 3
 - OS: Android 10
 - not rooted, no Magisk, no magic else
 - SD Maid 2/SE v 0.7.10-beta0

**Comment by NLPsixteen** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 9]
 - OS: [e.g. Android 17]
 - Root status [e.g. Rooted - Magisk v25.2]
 - SD Maid 2/SE version [e.g. v0.6.6-rc6]

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**
Add any other context about the problem here.
The electricity have bin Gone sins afternoon,i try use my Android but i see very bad and dont find My glasses in the Dark, i am sorry and apologize to all who was wonder what i was doing, sorry

**Comment by NLPsixteen** [comment]
Plz Delete all i did wrong, i can almost bot see anymore,i am very sorry
NLPsixteen
Peter Bergün Sweden

**Comment by NLPsixteen** [comment]
Problem now is to many hours with phone i csn not see anymore, i am sorry, it will never= happen again

**Comment by uli-on** [comment]
No problem, Peter, that's not a desaster :)
