### ISSUE TITLE
Add folder exclusion

### ISSUE THREAD

**Issue by ghost** [d4rken-org/sdmaid-se#317]
Currently, only whole application exclusion is supported. It is unfriendly to want to clean up individual files.

**Comment by d4rken** [comment]
Is this the same idea as #139?

**Comment by Iniabi** [comment]
> Is this the same idea as #139?

Sorry, I didn't notice this point when I submitted it. Now that I know, I think we can exclude the folder during post-scan processing. If it is still difficult to confirm the exclusion, there is no problem with keeping it as it is.

**Comment by d4rken** [comment]
Manual exclusion via #139 would allow to manually type something DCIM/Camera to exclude all paths like `/storage/emulated/0/DCIM/Camera/....` and `/storage/AAAA-FFFF/DCIM/Camera/....`.

Would this support your use-case?

**Comment by Iniabi** [comment]
> Manual exclusion via #139 would allow to manually type something DCIM/Camera to exclude all paths like `/storage/emulated/0/DCIM/Camera/....` and `/storage/AAAA-FFFF/DCIM/Camera/....`.
> 
> Would this support your use-case?
My situation is different. The cache files under certain game folders are very important and their absence would affect loading. I only need to exclude this folder.

**Comment by Iniabi** [comment]
> Manual exclusion via #139 would allow to manually type something DCIM/Camera to exclude all paths like `/storage/emulated/0/DCIM/Camera/....` and `/storage/AAAA-FFFF/DCIM/Camera/....`.
> 
> Would this support your use-case?

My situation is different. The cache files under certain game folders are very important and their absence would affect loading. I only need to exclude this folder.

**Comment by d4rken** [comment]
Doesn't excluding the app work? AppControl, find the app, exclude it from AppCleaner.

**Comment by Iniabi** [comment]
> Doesn't excluding the app work? AppControl, find the app, exclude it from AppCleaner.

Maybe I didn't explain clearly. Thank you for your patience. What I meant was that when cleaning up, I only want to exclude a single folder located in /data/media/0/Android/data/XXXXX/, not all files under the entire application path.

**Comment by d4rken** [comment]
That will also be possible with #139 you just have to make sure to stay a little vague, i.e.
create `Android/data/XXXXX` not `/data/media/0/Android/data/XXXXX` because internally the paths can be different depending on what access method is used.

Example: 

* Normal: `/storage/4BBD-D3E7/Android/data/some.app/specialfolder` 
* SAF: `content://com.android.externalstorage.documents/tree/4BBD-D3E7/Android/data/some.app/specialfolder`
* Root: `/data/media/0/Android/data/some.app/specialfolder`

It's all the same folder, just different way of access which is why creating a "file picker" to create exclusion is complicated.

But internally SD Maid converts all paths into "Segments", so the above three paths internally look like:

* Normal: Base `/storage/4BBD-D3E7`, Segments `[Android, data, some.app, specialfolder]` 
* SAF: Base `content://com.android.externalstorage.documents/tree/4BBD-D3E7/`, Segments `[Android, data, some.app, specialfolder]` 
* Root: Base `/data/media/0/`, Segments `[Android, data, some.app, specialfolder]` 

So an exclusion based on the later segments, i.e. `[Android, data, some.app, specialfolder]`  would work as exclusion for all access types, and would be fast too, less conversion to do for SD Maid.


Closing in favor of #139
