### ISSUE TITLE
A great feature idea for storage analyser fonction 

### ISSUE THREAD

**Issue by Cawca-Fr** [d4rken-org/sdmaid-se#345]
After getting the storage analyser results and select an app, we have 4 options "app code, app data, app Media and extra app files". In that screen it's could be great to add a '' refresh '' button for only analyse the storage specially for that app so values can be updated only for that app. And when we do back, instead of analysing all storage again the app can do a simple calculation of that new values to the global result for refreshing the list of apps showed in the result.

Here the screen of where I told about: 

[SmartSelect_20230604_140737_SD Maid SE.jpg](https://github.com/d4rken-org/sdmaid-se/assets/92250185/5ffca02e-f43e-4cfe-beca-43eb44ba13d8)

**Comment by d4rken** [comment]
The problem is that it's not possible to scan "just one app" if the results need to be accurate as SD Maid has to scan the whole storage to find out if there are new files that belong to the app.

Some file ownerships are not defined like "/sdcard/pathtofolder", but as "somefi*-123.zip" and to detect those SD Maid has to scan everything.
