### ISSUE TITLE
Accessibility permission error

### ISSUE THREAD

**Issue by AlanMartines** [d4rken-org/sdmaid-se#606]
Very good app, does what it promises.

Note that even giving accessibility permission #589, I always have to renew this permission, having to disable and enable it again.

As it's in beta, my feedback goes for improvements.

**Comment by cerberus6666** [comment]
you did sort the battery optimization right?

**Comment by AlanMartines** [comment]
Yes, it's unrestricted!

**Comment by AzRyCb** [comment]
> Aplikasi yang sangat bagus, melakukan apa yang dijanjikannya.
> 
> Perhatikan bahwa meskipun memberikan izin aksesibilitas #589 , saya selalu harus memperbarui izin ini, harus menonaktifkan dan mengaktifkannya lagi.
> 
> Karena ini masih dalam versi beta, tanggapan saya ditujukan untuk perbaikan.

same

**Comment by d4rken** [comment]
The service being disabled is mostly the system killing SD Maid.
If you are familiar with ADB or even Shizuku, then there are ways to let SD Maid automate ACS on/off when needed, see:
https://github.com/d4rken-org/sdmaid-se/wiki/Setup#acs-automatic-service-restart

If you think this is happening because of a crash, then reopen this and provide a debug log.
