### ISSUE TITLE
SD Maid 2/SE is unavailable on Google Play

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid-se#610]
Google terminated my developer account for incomprehensible reasons on August, 21st.

Appeal is in progress... :weary: 

As a temporary workaround you can switch to the GitHub releases, while your Google Play Pro Upgrade does not transfer, the GitHub release offers a "pay-what-you-want" upgrade flow, which can also be 0.

Stay tuned and hope for the best.

**Comment by vaimalaviya1233** [comment]
This is unreasonable termination if this goes on one day AI might really take over the whole world.

**Comment by optimatrix0** [comment]
I bought the lifetime version and now this one, Was my purchase in vain? because I had bought it on the play store and now it's not there anymore, so I ask you to send me the step by step on how to fix it fut

**Comment by optimatrix0** [comment]
I want to keep using it for as long as I paid for it, so I'm asking for help here.

**Comment by vaimalaviya1233** [comment]
> I bought the lifetime version and now this one, Was my purchase in vain? because I had bought it on the play store and now it's not there anymore, so I ask you to send me the step by step on how to fix it fut

As of right now pressing on donate or purchase (in-app) buttons temporarily activates, pro features for newer SD maid 2/SE however, I'm sure there will be some fix for it. I also wanted to purchase newer SD maid 2/SE however I only found out about it a week ago by that time it was already removed from playstore because of that god damn google Using AI detections. if not I would like to suggest developer a alternative like https://gumroad.com/ for implementation purchases and use fdroid or GitHub to release new versions however that will take lot of time as SD maid has been already implemented playstore in-app purchase to transition to new provider. As for old purchasers, I think it should still display in play store purchase history to use it to verify purchase.

**Comment by demetry14** [comment]
Glad to see you back on Google Play.  I noticed the original SD Maid no longer has the unlocked in play, so those of us that bought it cannot make it pro unless we previously backed up the unlocked app.

**Comment by vaimalaviya1233** [comment]
Hurray 🎊🎊🎊🥳🥳

**Comment by AgutinVBoy** [comment]
Congratulations 🎉

**Comment by RuslanYestemessov** [comment]
Congratulations 🎂

**Comment by d4rken** [comment]
Great to have this bug fixed :grin:
