### ISSUE TITLE
Default App Exceptions (Similar in SD Maid 1)

### ISSUE THREAD

**Issue by MarkyMarkDE** [d4rken-org/sdmaid-se#618]
for the following apps you should include non-deletable app exceptions for security purposes similar in SD Maid 1.

`com.starfinanz.mobile.android.pushtan`
Here you lose the device registration and have to request a new QR code from the bank (via postal service or in branch) and re-register the device - very bad!

`de.zollsoft.impfapp`
Here you lose the deposited COVID vaccination certificates, you have to delete all of them and scan them again - not bad but not nice either.

This list is not complete, you can expand it if necessary.

Pixel 7
Andoid 13 (Patches last of August 2023)
not rooted!
SD-Maid 0.11.0-beta0

**Comment by d4rken** [comment]
Which tools deletes the files? I would have guessed AppCleaner, but it seems weird that these apps store such information within cache directories?

Do you know the paths under which SD Maid finds the files?

**Comment by d4rken** [comment]
So it could also have been caused by other apps and not SD Maid? :thinking: 

A default exclusion is the "easy fix" here, but I'd like to first understand why (or if) SD Maid is the cause. If some of the filters target the wrong files, then this should be fixed at the root, so it's fixed for all cases.

If someone could reproduce this maybe with some demo certificates, that would be cool.

**Comment by d4rken** [comment]
Can you edit your post and add the device, android version, sd maid version and if you are running with root?

**Comment by MarkyMarkDE** [comment]
> Can you edit your post and add the device, android version, sd maid version and if you are running with root?

done in my initial comment.

**Comment by MarkyMarkDE** [comment]
> Which tools deletes the files? I would have guessed AppCleaner, but it seems weird that these apps store such information within cache directories?
> 
> Do you know the paths under which SD Maid finds the files?

yes it seems that my in initial comment listed apps stores "user datas" in public cache and not under /usr/.. or the named apps are able to delete complete all, but the funny, my music player have also a big cache (cover pictures, artist pictures, so on) and here is nothing deleted from any "cleaning" App.

**Comment by MarkyMarkDE** [comment]
and yes, i have added all options in SD Maid SE for deleting inc. activate the "Barrierefreiheitsdienst" and i have also set up a "cron job" for deleting caches every day at ca. 8 pm - yes this seems to work, if the display i inactive - it gets activated but "semi lighted" and i see SD Maid do his job but really slowly ...

**Comment by koyemyatoo2020** [comment]
run

**Comment by Noxello** [comment]
Hello,

I just found out if the system cleaner deletes the following files, Samsung Gallery won't be able to recover photos and videos that were put in the trash bin. I had this problem since switching to SD Maid SE, tested it and the problem occurred only after and every time I cleaned my phone and hasn't happened since I added the exception.

Files : 
/storage/101D-FE5D/Android/.Trash
/storage/emulated/0/Android/.Trash
They are considered Linux Files by the app.

Samsung Galaxy S20 FE
Android 13, OneUI 5.1, security patch of February 2024
Not rooted
SD Maid SE 0.21.0-beta0

**Comment by Ace7984** [comment]
I don't have a comment

**Comment by 20itsjustmax20** [comment]
> for the following apps you should include non-deletable app exceptions for security purposes similar in SD Maid 1.
> 
> `com.starfinanz.mobile.android.pushtan` Here you lose the device registration and have to request a new QR code from the bank (via postal service or in branch) and re-register the device - very bad!
> 
> `de.zollsoft.impfapp` Here you lose the deposited COVID vaccination certificates, you have to delete all of them and scan them again - not bad but not nice either.
> 
> This list is not complete, you can expand it if necessary.
> 
> Pixel 7 Andoid 13 (Patches last of August 2023) not rooted! SD-Maid 0.11.0-beta0



If I remove de.zollsoft.impfapp from the exclusion list is that all that I'd lose? COVID info ??

Thanks 🙏

**Comment by MarkyMarkDE** [comment]
> If I remove de.zollsoft.impfapp from the exclusion list is that all that I'd lose? COVID info ??
> 
> Thanks 🙏

@20itsjustmax20
In the past you have lost all COVID vaccine certificates in side the Impfapp. At moment this feature is not active in the App (but maybe come back), but not really sure, if we maybe delete more datas if we remove this exclusion. I'm also not sure, if all users of this App saves their Profile of this App periodically by self, so it would be restorable (exclude COVID Certificates - was never be part of the export file).
