### ISSUE TITLE
App cleaner automation isn't working on my device.

### ISSUE THREAD

**Issue by Shini369** [d4rken-org/sdmaid-se#627]
**Describe the bug**
The automation through accessibility get stuck on every app and jump to the next one and on. 

**To Reproduce**
1. Just run the App Cleaner

**Expected behavior**
It should click on "Armazenamento e Cache" and the clean it (screenshots bellow).

**Smartphone (please complete the following information):**
 - Device: Redmi 9 Power 
 - OS: Android 12 running MIUI Global 14.0.2
 - System Language: Portuguese (BR)
 - Root status: Non rooted
 - SD Maid 2/SE version: Beta 0.11.0-beta0

**Debug log**
[eu.darken.sdmse_logfile_1694828360219.log.zip](https://github.com/d4rken-org/sdmaid-se/files/12639669/eu.darken.sdmse_logfile_1694828360219.log.zip)

**Screenshots/Video**
In this screen it should click on "Armazenamento e Cache"
[Screenshot_2023-09-15-22-36-47-093_com android settings](https://github.com/d4rken-org/sdmaid-se/assets/34994035/a4cb9219-8feb-4400-b71d-3ed52628222a)

And it should open this menu:
[Screenshot_2023-09-15-22-36-52-181_com android settings](https://github.com/d4rken-org/sdmaid-se/assets/34994035/d65691c5-f174-46bb-abba-fcedcf650762)

**Additional context**
I believe it's just because the name of the correct menu is different on my device than the one the app was searching for. This was my first time doing a bug report, if I did something wrong pleazd teach me.

**Comment by d4rken** [comment]
Your bug report is just lovely 😍.

SD Maid extracts the label from the system APK, but for some reason the usual label is not used on your ROM:
```
Read com.android.settings:storage_settings from settings APK: Armazenamento
```

I've checked the code, and the issue could be that SD Maid uses the labels for older Android versions instead of newer ones. I've changed this to now depend on the currently used Android version. See #638

Please report back after the next update. ☕
