### ISSUE TITLE
Overly simplistic GUI and doesn't have previous capabilities 

### ISSUE THREAD

**Issue by fallendaemon** [d4rken-org/sdmaid-se#687]
I really prefer the original GUI, menu system and capabilities such as duplicate finder. This new interface seems way too cartoonish and not in keeping with a technical use utility. 

> Mornings in Sweden are always very cold and I'm not an early bird.

**Describe the solution you'd like**

> I would like it if SD Maid could make me coffee in the morning.

**Describe alternatives you've considered**

> I have considered making the coffee myself but both me and myself decided against it.

**Describe why this would be in the interest of all users**
Describe why this is not a niche feature, but would be a benefit for the majority of users.

> Everyone enjoys getting a hot beverage on a cold morning.

**Additional context**

**Comment by d4rken** [comment]
Some like it, some don't. There isn't really a way to make everyone happy here. If you have concrete ideas for a change, let me know, otherwise maybe open a discussion with other users on how the UI could be improved: https://github.com/d4rken-org/sdmaid-se/discussions

The Duplicates tool will likely make a comeback.
