### ISSUE TITLE
Thread count

### ISSUE THREAD

**Issue by Zojiq76** [d4rken-org/sdmaid-se#799]
I loved being able to change the thread count so now operations ran at the same time... Would love to be able to do that in the SE/new version, that is one of the main things that keeps me from using it so much ...

**Comment by d4rken** [comment]
Why do you need more than 2 operations to run at the same time?

Running all tasks in parallel is not beneficial.
Running too many tasks at once makes all tasks run slower because they compete for system resources.
This can be the difference between everything taking a few seconds more, to the whole device locking up because the system chokes on a maxed out disk IO.

The opposite seems more useful, a setting to ensure all tasks run sequential. This would help devices with low memory to avoid "OutOfMemory" errors.

SD Maids memory consumption peaks during execution of a task and is usually much lower at the end when "work resources" have been released.

**Comment by d4rken** [comment]
FYI, the "thread count" in SD Maid was more of a "worker/task count" setting. Each worker/task already uses multiple thread.

SD Maid had that setting to let users set it to `1`, but because it was used as direct numbers and not a `true/false` you could set it to higher than default levels too.

It creates too many edge cases, especially with out of memory errors. :frowning_face:

We could discuss increasing the default from `2` to `3`, but during my testing there was a large benefit to increasing it from 1 to 2, but not from 2 to 3.

We can redo the tests after the first 1.0 release though.

**Comment by d4rken** [comment]
Closing this for now, no specific action to take atm.
