### ISSUE TITLE
Avoid / Replace message "Die Einrichtung ist unvollständig" of Shizuku is selected and not available

### ISSUE THREAD

**Issue by rorar** [d4rken-org/sdmaid-se#938]
**Describe the bug**
After finishing the Einrichtungsassistent and selecting "Verwende Shizuku, wenn verfügbar", the message "Die Einrichtung ist unvollständig" sticks on the top of the main screen. 

This is a bit annoying and the user won't know what's up. 

It would improve the UX if the App would check the following steps; 
1. Is Shizuku installed? If yes, display a smaller message "Complete Shizuku Configuration" + Button "Open Shizuku" 
2. Are thenPermissions for SD Maid SE granted? If no, display a message "Grant Permission in Shizuku" 
3. The Option to suspend the both messages forever / set a reminder

**To Reproduce**
1. Go to 'Einrichtungsassistent' 
4. Click on 'Verwende Shizuku, wenn verfügbar'
5. Go to main screen
6. See message won't go away

**Expected behavior**
The message can be suspended xor gives more informations about the needed steps to complete the Einrichtungsassistent. 

**Smartphone (please complete the following information):**
 - Device: OPPO A54 5G
 - OS: 13
 - Root status: non-rooted 
 - SD Maid 2/SE version: v0.18.5

**Additional context**
If you're on the go, there won't always be a (trusted) Wifi connection to use ADB debugging + Shizuku. Therefore the message would pop up every time.

**Comment by d4rken** [comment]
> The message can be suspended 

Does the "dismiss" button on the setup card in the dashboard not work?

> xor gives more informations about the needed steps to complete the Einrichtungsassistent.

Could do, though I don't want to have to maintain setup instructions for Shizuku, that's up to the user and Shizuku and not SD Maids responsibility, right?

**Comment by d4rken** [comment]
> Is Shizuku installed? If yes, display a smaller message "Complete Shizuku Configuration" + Button "Open Shizuku"

I'm adding a button to open Shizuku from the setup card, but i don't think special setup behavior is otherwise needed here.

> Are thenPermissions for SD Maid SE granted? If no, display a message "Grant Permission in Shizuku"

I don't think SD Maid can know the permission state if Shizuku is not connecting with SD Maid.

> The Option to suspend the both messages forever / set a reminder

The `dismiss` button is working as expected and setting the state temporarily to "Don't use Shizuku" is also working. Extra reminders and handling seems too much. The dismiss feature works and is reset when entering the setup manually, and the setup options can also be changed at anytime.

> This is a bit annoying and the user won't know what's up.

The card will only show as "setup incomplete" if Shizuku is actually installed. Users who randomly select "use it" but don't have Shizuku, will not see "setup incomplete".

Not showing a hint that Shizuku is not working, if the user has enabled it in SD Maid, will just lead to numerous "why is this not working, oh Shizuku is not running" emails/support effort.

**Comment by rorar** [comment]
Thanks! Looks like a good solution :)
