### ISSUE TITLE
Pro version 

### ISSUE THREAD

**Issue by alabotski** [d4rken-org/sdmaid-se#962]
I have bought SD Maid SE almost year ago
All was fine

[Screenshot_20240127-214500](https://github.com/d4rken-org/sdmaid-se/assets/439337/7627d8cf-1e83-4a97-bf5e-4bbd50a6e3ca)

But after update to 0.19 I lost my pro subscription

[Screenshot_20240127-214636](https://github.com/d4rken-org/sdmaid-se/assets/439337/4745dee4-af37-4b32-98cc-6aec8cb091b6)

I tried reinstall, tried clean cache in Play Market. Nothing help

**Comment by stasiost** [comment]
I have the same problem

**Comment by drakoassault** [comment]
Same here 😔

**Comment by cromatn5** [comment]
Same here

**Comment by StefanDafni** [comment]
Ich habe das gleiche Problem. Mein Abo (Einmalkauf) ist weg. Cash leeren und Neustart funktioniert nicht. Was ist da los? Ich hatte schon die "alte SD"-App in der Pro-Version und im Okt.23 die Neue gekauft. Ich finde das nicht gut. Bitte dringend ändern.
![Screenshot_20240127_200400_Google Play Store](https://github.com/d4rken-org/sdmaid-se/assets/157916896/92f89f60-e35f-47db-8497-33d5e3fd634b)

**Comment by alexsokol79** [comment]
I have the same problem. Reboot, new install, clear cache of play store, but nothing works. 
![Screenshot_20240127-194411](https://github.com/d4rken-org/sdmaid-se/assets/157917115/1ca04618-7acb-400f-98c3-6b5c0c108106)

**Comment by Panas1989** [comment]
In version 0.19.1 this error will be corrected

**Comment by StefanDafni** [comment]
Und wo erhalte ich die Version 0.19.1. ??? Ich habe 0.19.0 aber im Play Store gibt es kein Update.Danke für die Hilfe StefanDafniKüchengarn.de
Stefan Hettinger
Seefelder Straße 70
D-82211 Herrsching
F: +49 8152 98 93 59
M: +49 172 833 27 36 
-------- Ursprüngliche Nachricht --------Von: Panas1989 ***@***.***> Datum: 27.01.24  20:20  (GMT+01:00) An: d4rken-org/sdmaid-se ***@***.***> Cc: StefanDafni ***@***.***>, Comment ***@***.***> Betreff: Re: [d4rken-org/sdmaid-se] Pro version  (Issue #962) 
In version 0.19.1 this error will be corrected

**Comment by Guenni1975** [comment]
Selbes Problem hier, seit Update ist der Pro Status weg. Neustart, Cache leeren und Neuinstallation nichts hat geholfen, bitte korrigieren!

**Comment by d4rken** [comment]
See #959

The bug is fixed in v0.19.1

@StefanDafni The update (v0.19.1) is waiting for Google's review

**Comment by StefanDafni** [comment]
Sehr geehrter Herr Urhahn,mich stört Ihre unsägliche Arroganz. Was Sie hier "veranstalten" nennen deutsche und europäische Gerichte Betrug - Software verkaufen, aber dann nicht liefern. Das geht nicht!!!Deshalb schlage ich zur Güte folgendes vor: Sie senden mir binnen der nächsten Stunden, also heute 28.01.2024 bis spätestens 18:00 Uhr per Email einen Link, wo ich die funktionierende, vollständige Pro-Software herunter laden kann. alternativ können Sie mir auch bis zur selben Frist meine bezahlten € 5,89 erstatten, dann hat sich das Thema SD-Maid endgültig erledigt.Falls Ihnen gar nichts Recht sein soll - oder anders formuliert, wenn Sie Ihrem Verkauf und Ihren gesetzlichen Pflicht aus unserem Dienstleistungsvertrag nicht bis zum 28.01.2024, 18:00 Uhr nachkommen, erstatte ich Anzeige wegen Betrugs bei der Staatsanwaltschaft Aachen und melde Google Ihren Internet-Betrug. Dann wird es eben ganz Dark(en) für Sie.Mit freundlichen GrüßenStefan HettingerKüchengarn.de
Stefan Hettinger
Seefelder Straße 70
D-82211 Herrsching
F: +49 8152 98 93 59
M: +49 172 833 27 36
-------- Ursprüngliche Nachricht --------Von: Matthias Urhahn ***@***.***> Datum: 27.01.24  20:41  (GMT+01:00) An: d4rken-org/sdmaid-se ***@***.***> Cc: StefanDafni ***@***.***>, Mention ***@***.***> Betreff: Re: [d4rken-org/sdmaid-se] Pro version  (Issue #962) 
See #959
The bug is fixed in v0.19.1
@StefanDafni The update (v0.19.1) is waiting for Google's review

**Comment by Guenni1975** [comment]
Wenn Sie hier mal mitlesen würden, dann hätten Sie gelesen, dass es hier leider einen Bug in der aktuellen Version gibt. Das Problem, das die Pro Version nicht funktioniert hat gerade jeder. Ein Update ist bereits raus, wartet allerdings noch auf Freischaltung von Google. Da kann der Programmierer auch nichts dafür. Es ist Sonntag. Und da dauert alles nunmal etwas länger wenn man Pech hat. Ihre Drohung gegen den Programmierer ist ein Witz, da kommen Sie vor keinem Gericht der Welt mit durch. Warten Sie einfach bis morgen, dann wird die Version sicher freigegeben und es ist alles Friede, Freude, Eierkuchen. Einen schönen Sonntag Ihnen noch!

**Comment by StefanDafni** [comment]
Was zu beweisen war: Arroganz. Ich brauche kein Gericht, die Staatsanwaltschaft macht das ganz alleine. Aber was will man von jemandem erwarten, der nur 0 und 1 versteht.

**Comment by Guenni1975** [comment]
Ich bin nicht der Programmierer, nur als Info. Sondern auch nur ein Nutzer. Ich warte auch auf Veröffentlichung der neuen Version, weil meine Pro Version nicht mehr funktioniert. Nutze SD Maid seit Jahren und wenn jetzt mal ein doofer Bug drin ist, auch Programmierer sind nur Menschen. Aber man kann es auch übertreiben. Einen schönen Sonntag noch, genießen Sie diesen und warten Sie auf die Veröffentlichung der Version 0.19.1 dann ist Ihr Problem behoben und die Welt sieht gleich wieder viel riesiger aus! 😁
